### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by chipzoller** [kyverno/playground#181]
Low priority, but mobile support would be a nice to have feature.

**Comment by fjogeleit** [comment]
Did you try mobile screen? The layout is responsive to its basically usable on mobile.

do you have concrete improvements which are needed?

**Comment by fjogeleit** [comment]
There is, they are under the policy panel, but yes the scrolling is a bit more difficult due to the additional scrolling behavior of the editor
<img width="493" alt="Bildschirmfoto 2023-05-17 um 12 39 58" src="https://github.com/kyverno/playground/assets/16627596/b2457e1e-7f57-46ea-a660-b076926cc754">

<img width="493" alt="Bildschirmfoto 2023-05-17 um 12 39 27" src="https://github.com/kyverno/playground/assets/16627596/98c51c44-bd15-4eb7-979b-f3b8e7ec5445">

**Comment by fjogeleit** [comment]
I will work on this, maybe I let more space left and right. To have more space to scroll outside of the editor

**Comment by fjogeleit** [comment]
I added more space on the right site, to have more space to scroll the screen (instead of the editor content). Does this help?

**Comment by chipzoller** [comment]
Helps quite a bit. Considering this issue resolved.
