### ISSUE TITLE
Context Variable are broken in playground

### ISSUE THREAD

**Issue by tip-dteller** [kyverno/playground#617]
Hi,
I've been testing out some policies and i've noticed that setting Context Variables seems to be broken
even when using a Tutorial Policy
![Screenshot 2024-02-07 at 10 42 52](https://github.com/kyverno/playground/assets/128965284/23a62f12-821e-43e7-9298-2113abb173d0)

has anyone else experienced this issue? 
please provide some clarity :) 
Thanks!!

**Comment by fjogeleit** [comment]
Hey, thanks for reporting. I'll take a look.

**Comment by fjogeleit** [comment]
Sorry for the late response, the example policy in the kyverno/policies has changed and we missed to add the new allhosts variable. Because the playground is not able to execute apiCalls we need to mock them, which is possible under: Advanced -> Context

<img width="1674" alt="Bildschirmfoto 2024-07-23 um 12 35 45" src="https://github.com/user-attachments/assets/eac6f60f-d811-4ce1-a532-a893c405befe">
